### ISSUE TITLE
Tests failing, problems on Windows machine

### ISSUE THREAD

**Issue by tompazourek** [stevoland/grunt-es6-module-wrap-default#1]
I discovered a bug when using this task in one of the dependant projects (react-bootstrap). When using the grunt task on a Windows machine, the generated AMD/CJS modules have wrong path (that has backslash in them):

Example (react-bootstrap\cjs\BootstrapMixin.js):

``` js
var BootstrapMixin = require('./transpiled\BootstrapMixin').default;
module.exports = BootstrapMixin
```

_Node then either treats the backslash as an escaping character or it cannot handle it at all (not sure)._

I tried to fix the problem (first by the trivial replacing of \ by /), but I discovered that the tests do not run at all. The resulting error from grunt is:

```
Running "nodeunit:tests" (nodeunit) task
Testing es6_module_wrap_default_test.jsFF
>> es6_module_wrap_default - default_options
>> Message: should describe what the default behavior is.
>> Error: 'var testing = require(\'./../test/fixtures/testing\').default;\nmodule.exports = testing' == 'Testing, 1 2 3.'
>> at Object.exports.es6_module_wrap_default.default_options (test\es6_module_wrap_default_test.js:35:10)
>> at Object.exports.es6_module_wrap_default.setUp (test\es6_module_wrap_default_test.js:28:5)

>> es6_module_wrap_default - custom_options
>> Message: should describe what the custom option(s) behavior is.
>> Error: 'var testing = require(\'./../test/fixtures/testing\').default;\nmodule.exports = testing' == 'Testing: 1 2 3!!!'
>> at Object.exports.es6_module_wrap_default.custom_options (test\es6_module_wrap_default_test.js:44:10)
>> at Object.exports.es6_module_wrap_default.setUp (test\es6_module_wrap_default_test.js:28:5)

Warning: 2/2 assertions failed (35ms) Use --force to continue.
```

Are the tests broken or is it just my environment?

Anyway, the task is not working on Windows and it could be probably fixed with almost no effort. :-)

**Comment by stevoland** [comment]
Hi, yeah ignore the tests, there aren't any!

They're just the default grunt plugin ones. Please submit a PR if you can.

Thanks!
